package rules;

import com.ftn.model.Fragrance;
import com.ftn.model.AccumulateFragrance;

rule "Accumulate min max avg brand"
no-loop
agenda-group "acc_rule"
    when
        $af: AccumulateFragrance()
        
        Number($minPrice: intValue) from accumulate (
            Fragrance( getDesigner().equalsIgnoreCase($af.getBrandName()) , $price: price) from $af.getFragrances(),
            min($price));
        Number($maxPrice: intValue) from accumulate (
            Fragrance( getDesigner().equalsIgnoreCase($af.getBrandName()) , $price: price) from $af.getFragrances(),
            max($price));
        Number($avgPrice: doubleValue) from accumulate (
            Fragrance( getDesigner().equalsIgnoreCase($af.getBrandName()) , $price: price) from $af.getFragrances(),
            average($price));
    then
        modify($af) {setMinPrice($minPrice),
        setMaxPrice($maxPrice),
        setAvgPrice($avgPrice) };
        System.out.println("Min: "  + $minPrice);
        System.out.println("Max: "  + $maxPrice);
        System.out.println("Avg: "  + $avgPrice);
end;

